-- Update pricing_configs defaults to match new TKBSO standards (Jan 2025)
-- Remove multipliers concept - use line items for scope variations

ALTER TABLE public.pricing_configs 
  ALTER COLUMN kitchen_ic_per_sqft SET DEFAULT 128,
  ALTER COLUMN kitchen_cp_per_sqft SET DEFAULT 190,
  ALTER COLUMN bath_ic_per_sqft SET DEFAULT 245,
  ALTER COLUMN bath_cp_per_sqft SET DEFAULT 385,
  ALTER COLUMN closet_ic_per_sqft SET DEFAULT 55,
  ALTER COLUMN closet_cp_per_sqft SET DEFAULT 90,
  ALTER COLUMN tile_wall_ic_per_sqft SET DEFAULT 20,
  ALTER COLUMN tile_wall_cp_per_sqft SET DEFAULT 39,
  ALTER COLUMN tile_floor_ic_per_sqft SET DEFAULT 5.5,
  ALTER COLUMN tile_floor_cp_per_sqft SET DEFAULT 12,
  ALTER COLUMN tile_shower_floor_ic_per_sqft SET DEFAULT 6,
  ALTER COLUMN tile_shower_floor_cp_per_sqft SET DEFAULT 14,
  ALTER COLUMN waterproofing_ic_per_sqft SET DEFAULT 6,
  ALTER COLUMN waterproofing_cp_per_sqft SET DEFAULT 13,
  ALTER COLUMN demo_shower_only_ic SET DEFAULT 900,
  ALTER COLUMN demo_shower_only_cp SET DEFAULT 1450,
  ALTER COLUMN demo_small_bath_ic SET DEFAULT 1300,
  ALTER COLUMN demo_small_bath_cp SET DEFAULT 2050,
  ALTER COLUMN demo_large_bath_ic SET DEFAULT 1650,
  ALTER COLUMN demo_large_bath_cp SET DEFAULT 2500,
  ALTER COLUMN demo_kitchen_ic SET DEFAULT 1750,
  ALTER COLUMN demo_kitchen_cp SET DEFAULT 2800,
  ALTER COLUMN plumbing_shower_standard_ic SET DEFAULT 2225,
  ALTER COLUMN plumbing_shower_standard_cp SET DEFAULT 3425,
  ALTER COLUMN plumbing_extra_head_ic SET DEFAULT 625,
  ALTER COLUMN plumbing_extra_head_cp SET DEFAULT 1100,
  ALTER COLUMN plumbing_tub_freestanding_ic SET DEFAULT 3300,
  ALTER COLUMN plumbing_tub_freestanding_cp SET DEFAULT 4800,
  ALTER COLUMN plumbing_toilet_cp SET DEFAULT 690,
  ALTER COLUMN electrical_vanity_light_cp SET DEFAULT 350,
  ALTER COLUMN electrical_kitchen_package_cp SET DEFAULT 1750,
  ALTER COLUMN paint_patch_bath_ic SET DEFAULT 800,
  ALTER COLUMN paint_full_bath_ic SET DEFAULT 1200,
  ALTER COLUMN paint_full_bath_cp SET DEFAULT 1900,
  ALTER COLUMN glass_shower_standard_cp SET DEFAULT 2100,
  ALTER COLUMN glass_panel_only_cp SET DEFAULT 1450,
  ALTER COLUMN quartz_cp_per_sqft SET DEFAULT 50,
  ALTER COLUMN min_job_ic SET DEFAULT 10500,
  ALTER COLUMN min_job_cp SET DEFAULT 15000;