-- Add structural/complex work pricing fields to pricing_configs
ALTER TABLE public.pricing_configs
  ADD COLUMN IF NOT EXISTS wall_removal_ic numeric DEFAULT 1800,
  ADD COLUMN IF NOT EXISTS wall_removal_cp numeric DEFAULT 2800,
  ADD COLUMN IF NOT EXISTS door_relocation_ic numeric DEFAULT 1400,
  ADD COLUMN IF NOT EXISTS door_relocation_cp numeric DEFAULT 2200,
  ADD COLUMN IF NOT EXISTS door_closure_ic numeric DEFAULT 700,
  ADD COLUMN IF NOT EXISTS door_closure_cp numeric DEFAULT 1100,
  ADD COLUMN IF NOT EXISTS entrance_enlargement_ic numeric DEFAULT 1100,
  ADD COLUMN IF NOT EXISTS entrance_enlargement_cp numeric DEFAULT 1700,
  ADD COLUMN IF NOT EXISTS soffit_removal_ic numeric DEFAULT 950,
  ADD COLUMN IF NOT EXISTS soffit_removal_cp numeric DEFAULT 1500,
  ADD COLUMN IF NOT EXISTS shower_enlargement_ic numeric DEFAULT 2000,
  ADD COLUMN IF NOT EXISTS shower_enlargement_cp numeric DEFAULT 3200,
  ADD COLUMN IF NOT EXISTS tub_relocation_ic numeric DEFAULT 3000,
  ADD COLUMN IF NOT EXISTS tub_relocation_cp numeric DEFAULT 4800,
  ADD COLUMN IF NOT EXISTS toilet_relocation_ic numeric DEFAULT 1400,
  ADD COLUMN IF NOT EXISTS toilet_relocation_cp numeric DEFAULT 2200,
  ADD COLUMN IF NOT EXISTS alcove_builtin_ic numeric DEFAULT 1050,
  ADD COLUMN IF NOT EXISTS alcove_builtin_cp numeric DEFAULT 1650,
  ADD COLUMN IF NOT EXISTS closet_reframe_ic numeric DEFAULT 1400,
  ADD COLUMN IF NOT EXISTS closet_reframe_cp numeric DEFAULT 2200,
  ADD COLUMN IF NOT EXISTS drywall_ic_per_sqft numeric DEFAULT 9,
  ADD COLUMN IF NOT EXISTS drywall_cp_per_sqft numeric DEFAULT 15;